name: Run code tests on Pull Request or Push

on:
  # Runs for pushes and pull requests,
  #  but don't run these when only some config is changed.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      node_version:
        description: 'NodeJS version'
        required: true
        default: '18.x'

jobs:
  test:
    name: Run tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version || '18.x' }}
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Deps
        run: cat package-lock.json

      - name: Lint code for code-style errors
        run: npm run lint