codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  precision: 2
  round: down
  range: "0...100"
  
  status:
    project:
      default:
        # Adjust target coverage based on your project needs
        target: auto
        threshold: 1%
        base: auto
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
        
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/__tests__/**"
  - "**/test/**"
  - "**/node_modules/**"
  - "**/build/**"
  - "**/dist/**"
  - "**/*.d.ts"