name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 20
    - name: Build
      run: |
        npm ci
        npm run build
        
    - name: Read package.json
      uses: zvonimirsun/read-package-version-actions@v2
      id: package-version

    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        file-path: zip/twitter-enhanced-extension-${{ steps.package-version.outputs.version }}.zip
        extension-id: 'cdcjmkiabmominbckhhcbjleidhddjfc'
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
