name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20


    - name: Configure .env file
      id: generate_env_file
      env:
        GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
        GA_API_SECRET: ${{ secrets.GA_API_SECRET }}
      run: |
        set -e
        mv .env.example .env
        sed -i "s/GA_MEASUREMENT_ID=/GA_MEASUREMENT_ID=$GA_MEASUREMENT_ID/" .env
        sed -i "s/GA_API_SECRET=/GA_API_SECRET=$GA_API_SECRET/" .env
                 


    - name: Build
      run: |
        npm ci
        npm run build
        
    - name: Read package.json
      uses: zvonimirsun/read-package-version-actions@v2
      id: package-version

    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        file-path: zip/twitter-enhanced-extension-${{ steps.package-version.outputs.version }}.zip
        extension-id: 'cdcjmkiabmominbckhhcbjleidhddjfc'
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
